### ISSUE TITLE
Module not found: Can't resolve 'async_hooks'

### ISSUE THREAD

**Issue by 0xbid** [vordgi/next-impl-getters#22]
Pretty sure it just needs to be added to package.json

**Comment by vordgi** [comment]
What version of Node.js are you using?

**Comment by vordgi** [comment]
And are you sure that server getters are not used in client components?

**Comment by 0xbid** [comment]
Hey @vordgi, my version is Node 18.x

> And are you sure that server getters are not used in client components and not assembled into client bundle?

Not end-to-end, but the wrapper of it is used. Here is my setup:

UserProvider.tsx
```ts
import createServerContext from 'next-impl-getters/create-server-context';
import { User } from '@/app/_types/types';

export interface UserContextProps {
    children: React.ReactNode;
    initialUser: User;
}

export const UserContext = createServerContext<{ user: User | null }>();

export const UserProvider = ({ children, initialUser }: UserContextProps) => {
    return <UserContext.Provider value={{ user: initialUser }}>{children}</UserContext.Provider>;
};
```

layout.tsx
```ts
const user = await getUser(); // api call

<UserProvider initialUser={user}>
```


user.ts
```ts
import getServerContext from 'next-impl-getters/get-server-context';
import { UserContext } from '@/app/_components/providers/UserProvider';
import { User } from '../_types/types';

export const useUser = (): User | null => {
    const context = getServerContext(UserContext);
    return context ? context.user : null;
};

```

My actual app pages / components example usage:
```
const user = useUser();
```
But these components can be both server or client components. Is that not allowed? And if not, whats the recommended solution to just make one API call `getUser();` at the root layout level and retrieve that information across all pages / components?

I guess an alternative not use a provider at all, and just user the same API call in other pages, and just pass `user` down to all the components that need it. But I am not sure if Next will de-dupe the same API call across different pages / layouts.

**Comment by vordgi** [comment]
Yes. To be honest, I thought a lot about this point - should this work on both the client and the server. But in the end I decide no. It will have a lot of problems, hidden logic and will be difficult to debug.

In your case, you can create both a server context and a client context and work with both of them.

And one more thing - be careful with contexts in layout. It will not be rerendered (next.js specifics) and there may be artifacts that the user has changed/left, but everything in the layout remains unchanged


> But I am not sure if Next will de-dupe the same API call across different pages / layouts.
They rewrote fetch for this purpose. That is, fetch is optimized in this regard, but all other solutions are not

**Comment by 0xbid** [comment]
> They rewrote fetch for this purpose. That is, fetch is optimized in this regard, but all other solutions are not

Thanks, honestly just doing the multiple calls and passing user down sounds easier.

> and one more thing - be careful with contexts in layout. It will not be rerendered (next.js specifics) and there may be artifacts that the user has changed/left, but everything in the layout remains unchanged

This is pretty annoying, esp with typical user cookies, but I've been getting around it by doing `window.location.reload` on login / logout. Is there any better way?

**Comment by vordgi** [comment]
Maybe router.refresh() will work

**Comment by 0xbid** [comment]
> Maybe router.refresh() will work

Doesn't seem to reload that actual layout though

**Comment by 0xbid** [comment]
https://nextjs.org/docs/app/api-reference/functions/revalidatePath#revalidating-a-specific-url this is the best I found, pretty good actually it doesn't turn the page blank momentarily link window.location.reload and it clears a specific layout.tsx

**Comment by vordgi** [comment]
I close the task because there is no error. Thanks for the feedback, I created a new issue to add an example with a provider with client and server contexts (#27)
