### ISSUE TITLE
Why `AsyncLocalStorage` instead of `cache`

### ISSUE THREAD

**Issue by markomitranic** [vordgi/next-impl-getters#28]
Hey there @vordgi thanks for some great contributions :) 

I'm just trying to learn more about these things and am aware of ye olde `createServerContext` function from canary and how it was discontinued. I am also aware that many library authors that needed a server context to avoid prop drilling or pass state to faraway components (for example `next-intl`) used react's `cache` function to get a shared store.

They'd have us hydrate it with information within every layout and every page, since these may be rendered separately and at different times and can't share state - but the component tree inside them would have a shared state thanks to `cache`. There are many blogposts on the topic created since, explaining how to make getter/setter patterns with it.

Your approach was the first time I've seen `AsyncLocalStorage` used ever, and the first time I've seen it used to replace `cache`. Can you please, pretty please, tell me more about the two. Why did you go with `AsyncLocalStorage` over `cache`, is it something that the Next.JS team is also doing, does it in any way help solve the layout/page issue etc.

thank you <3

**Comment by vordgi** [comment]
Hello. Oh, that's simple question)

Cache works for whole process (_in the case of next.js, for the entire page_). So it can be used to create a page context, but not React's `useContext` alternative. While `AsyncLocalStorage` create exactly the behavior I need.

Next.js uses `AsyncLocalStorage`, but for different processes - to create a shared context for the entire page at build time (
_and I use their storage in other getters_).

This package does not solve the layout problem. Nothing will solve the layout problem, they should just be perceived as an html template for embedding a react application.

**Comment by markomitranic** [comment]
Than you for the answer @vordgi :) I've read it multiple times, as well as the repo readme.

Got it, pages and layouts are separate things, I have no problem with that, especially ever since I've learned the `ServerHydratedContext` pattern where we hydrate a client layout context remotely from the page, by injecting server data into it.

--

I've learned from you that `cache` lives and dies with the individual process, for example building (or rendering) the page (or layout), while `AsyncLocalStorage` can span and share state across multiple processes.

I got intrigued by that second part. 

Looking at your code, you use the `AsyncLocalStorage` exported from `next/dist/client/components/static-generation-async-storage.external` to access Next's internal values during static and server rendering. That makes perfect sense for your case. 

--

I have 2 more questions, I'm very thankful for your response:

I'm trying to understand what would be the use case of spanning multiple processes, for us others, for storing and getting values in the user-space. It seems like `cache` is sufficient for all use cases I've seen so far (not for yours, obviously, because you need to fetch nextjs internal vars).

Also, silly question, but, how do other processes know which `AsyncLocalStorage` to use? In your code you are importing a reference from `next/dist/client/components/static-generation-async-storage.external`, that is easy to understand. But I also see you creating a new instance inside `create-server-context.tsx`, without any "key name" or reference. Does that mean that `AsyncLocalStorage` is a shared similar to a singleton, in the whole runtime, and every time you access it you get the same "global" set of values, including those from NextJS?

**Comment by vordgi** [comment]
> while AsyncLocalStorage can span and share state across multiple processes.
Not exactly. You can create this instance from above and use it for different processes. I don't do this for server contexts.

> I'm trying to understand what would be the use case of spanning multiple processes
Next.js now runs the build in multiple processes. AsyncLocalStorage or ServerContext does not create new processes.

> you creating a new instance inside create-server-context.tsx
I'm creating a new instance of not nextjs AsyncLocalStorage. I'm using native node.js Storage. And then the magic of nodejs - that new store is only accessible below the function tree.

**Comment by markomitranic** [comment]
@vordgi I've been playing around with this pattern since you answered, and I've replicated it using `cache`. I hope this comes in useful to someone who reads this thread in the future ;) Also, do you have any comments on why or why not?

```ts
// createServerContext.ts
import React from 'react';
import { cache } from 'react';

type ServerContext<T> = {
    Provider: ({ children, value }: { children: React.ReactNode; value: T; }) => React.ReactNode;
    Consumer: ({ children }: { children: (context: T | undefined) => React.ReactNode; }) => React.ReactNode;
    _storage: () => { value: T | undefined; };
    _defaultValue: T | undefined;
};

/**
 * Creates a new datastore for a given server context.
 */
export function createServerContext<T>(defaultValue?: T): ServerContext<T> {
    throwInClient();

    const getCache = cache<() => {value: T | undefined}>(() => ({ value: undefined }));
    return {
        Provider: ({ children, value }) => {
            getCache().value = value;
            return children;
        },
        Consumer: ({ children }) => {
            const store = getCache();
            return children(store ? store.value : defaultValue);
        },
        _storage: getCache,
        _defaultValue: defaultValue,
    }
}

/**
 * Fetches a value present in a given server context.
 */
export function getServerContext<T>({ _storage, _defaultValue }: ServerContext<T>) {
    throwInClient();
    const store = _storage();
    if (!store) return _defaultValue;
    return store.value;
}

/**
 * Throws if called within a client component environment.
 * Useful to help prevent mistakes.
 */
export function throwInClient(): void | never {
    // If useState is defined we're in a client component
    if (Boolean(React.useState)) {
      throw new Error(`createServerContext only works in Server Components`);
    }
  }
```

Then, I've used it with your Isomorphic example and it works just fine, here is an example of usage:
```tsx
// ServerContext.tsx
import {getServerContext, createServerContext} from "@/CreateServerContext/createServerContext";
import { LocaleContextParams } from "./LocaleContextProvider";

export const LocaleServerContext = createServerContext<string | null>(null);

export function LocaleServerContextProvider({
  locale,
  children,
}: LocaleContextParams) {
  return (
    <LocaleServerContext.Provider value={locale}>
      {children}
    </LocaleServerContext.Provider>
  );
}

export function getLocale() {
  return getServerContext(LocaleServerContext);
}
```

**Comment by vordgi** [comment]
@markomitranic 

Now the contexts are covered with tests. I ran this solution through them. And, as expected, it works globally, and not in the Provider’s scope.

It's just that the `cache` is made to cache data on the entire page, and not usable for the context.
