### ISSUE TITLE
Use getSearchParams() without force-dynamic for draft mode requests ?

### ISSUE THREAD

**Issue by MangoMarcus** [vordgi/next-impl-getters#39]
Hi there,

I'm not using `export const dynamic = 'force-dynamic'` as I'm trying to use static rendering where possible, I understand though that unlike `getPathname()`, `getSearchParams()` requires dynamic rendering as the search params can only be known at request time, not build time.

However I wondered if it's still possible to use it in [draft mode](https://nextjs.org/docs/app/building-your-application/configuring/draft-mode), which **is** rendered at request time, eg.

```ts
import { getSearchParams } from 'next-impl-getters/get-search-params';
import { draftMode } from 'next/headers';

const { isEnabled } = draftMode();

if (isEnabled) {
  // Page is being dynamically rendered
  const token = getSearchParams({ ignoreDynamicOptionErrors: true }).get('token');
} else {
  // Page is being statically rendered

}
```

This does work locally, but not on a preview deployment on Vercel.

Is this possible? Or am I missing something

Thanks!

**Comment by vordgi** [comment]
Hello! Thanks for the issue, this is a really interesting and important point.

Apparently next.js removes some params specifically for Vercel 😬

![image](https://github.com/vordgi/next-impl-getters/assets/91429106/f47d53ed-68ed-40c8-a8f5-b5e5b8b69660)

As an option, I can suggest adding a url header to the middleware and extract params from it, taking it from headers (https://github.com/vercel/next.js/issues/43704#issuecomment-1411186664)

_In any case, I’ll try to dig deeper and maybe to figure it out_

**Comment by vordgi** [comment]
Well. After researching decided to mark this getter as deprecated. There are too many situations where next.js already trims or may trim params.

Instead, it will be recommended to use a solution via middleware and get-page-config (_as written [here](https://github.com/vordgi/next-impl-getters/blob/0b0737c0fe9372d33bb48c2e4ea9a2fad51583aa/docs/get-search-params.md)_).

Thanks again for writing about the problem!

**Comment by MangoMarcus** [comment]
Hey @vordgi , thanks for the speedy response and action! Interesting that NextJS removes those params.

Thanks for the middleware suggestion, that was very helpful. I've got it working now, I didn't realise that middleware doesn't _necessarily_ opt you in to dynamic rendering for a page so that does the job perfectly for me.

Thanks!
